services:
    jenkins:
        build: ./jenkins-setup
        image: jenkins/jenkins:lts
        container_name: jenkins-laravel
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - ./jenkins-setup/casc.yaml:/var/jenkins_home/casc_configs/casc.yaml
        environment:
            - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/casc.yaml
volumes:
    jenkins_home:
        driver: local
